on:
  create:
    branches:    
        - 'feature/**'
        - 'epic/**'
  push:
    branches:    
        - 'feature/**'
        - 'epic/**'

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT }}
        script: |
          const reference = String(context.ref).split("/");
          const nameComponents = reference.slice(-2);
          const featureOrEpic = nameComponents[0];
          const featureIdentifier = nameComponents[1].replace(/[^a-zA-Z0-9\-]/g, '');
          const shortSha = String(context.sha).slice(0, 7);
          const imageTag = `${featureOrEpic}-${featureIdentifier}--${shortSha}`;
          await github.rest.actions.createWorkflowDispatch({
            owner: 'placeit-envato',
            repo: 'providentia',
            workflow_id: 'commercial-feature-create.yml',
            ref: 'main',
            inputs: {
              environment: 'feature',
              applicationName: 'commercial',
              applicationSuffix: featureIdentifier,
              namespace: featureIdentifier,
              image: `025192112846.dkr.ecr.us-east-1.amazonaws.com/commercial:${imageTag}`,
              hostname: `${featureIdentifier}.feature.placeitcode.net`,
              revision: String(context.ref)
            }
          })
