on:
  delete:
    branches:    
        - 'feature/**'
        - 'epic/**'
  push:
    branches:    
        - 'feature/**'
        - 'epic/**'

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - id: generate
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);
